name: Gradle CI with actions
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.5.0

      - name: Build with Gradle
        run: |
          pwd
          ./gradlew build
          cd gradle-examples/gradle-example-minimal
          ./gradlew build
        working-directory: gradle-examples/gradle-example-minimal
