name: Gradle CI with actions
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.5.0
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: https://psemea.jfrog.io
        with:
          # Name of the OIDC provider as specified on the OIDC integration page in the JFrog Platform
          oidc-provider-name: mathieup-github
      - name: Build with Gradle
        working-directory: gradle-examples/gradle-example-minimal
        run: |
          jf gradle-config
          jf gradle clean artifactoryPublish

